server:
  port: 8664

spring:
  application:
    name: CUSTOMER
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
